targets:
  $default:
    builders:
      graphql_codegen:
        options:
          addTypename: false
          scalars:
            URL:
              type: String
            Datetime:
              type: Datetime
              fromJsonFunctionName: customDateTimeFromJson
              toJsonFunctionName: customDateTimeToJson
              import: package:allup_user_app/scalars.dart
            CurrencyValue:
              type: CurrencyValue
              fromJsonFunctionName: currencyValueFromJson
              toJsonFunctionName: currencyValueToJson
              import: package:allup_user_app/scalars.dart
            # LocalTime:
            #   type: LocalTime
            #   fromJsonFunctionName: localTimeFromJson
            #   toJsonFunctionName: localTimeToJson
            #   import: package:allup_user_app/scalars.dart

          clients:
            - graphql
            - graphql_flutter
