name: allup_user_app
description: Allup app for customers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  custom_refresh_indicator: ^3.0.0
  equatable: ^2.0.5
  # firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.12.4
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.1
  graphql: ^5.2.0-beta.7
  graphql_flutter: ^5.2.0-beta.6
  http: ^1.2.1
  hydrated_bloc: ^9.1.4
  intl: ^0.18.0
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.13.11
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/skinnable_images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf

    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
    - family: Bebas
      fonts:
        - asset: assets/fonts/Bebas-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
