name: allup_user_app
description: Allup app for customers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  equatable: ^2.0.5
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.12.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  go_router: ^13.1.0
  graphql: ^5.2.0-beta.7
  graphql_flutter: ^5.2.0-beta.6
  http: ^1.2.0
  intl: ^0.18.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.13.11
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/skinnable_images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf

    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
    - family: Bebas
      fonts:
        - asset: assets/fonts/Bebas-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
